my_list =[10,20,30,40]
print(my_list)
my_list.insert(1,15)
print(my_list)
my_list.extend([50,60,70])
print(my_list)
my_list.pop(-1)
print(my_list)
my_list.sort()
print(my_list)
index_of_30 = my_list.index(30)
print("Index of 30 in my_list:", index_of_30)
print("Final my_list:", my_list)